// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vomyzzqdoksohmegnpez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvbXl6enFkb2tzb2htZWducGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODg3MzUsImV4cCI6MjA3MTY2NDczNX0.OGwx8B_Oc8s6Ckg6fXLv_41UbSzic5aGsihBJejqiBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});